/* Вывести на экран все возможные комбинации слов "мама", "мыла", "раму".
*/
public class Main {
    public static void main(String[] args) {

        String a = "Мама";
        String b = "Мыла";
        String c = "Раму";
        {
            System.out.println(a + b + c);
        }

        {
            System.out.println(b + c + a);
        }

        {
            System.out.println(c + a + b);
        }
        {
            System.out.println(c + b + a);
        }
        {System.out.println(a+c+b);
    }
        System.out.println(b+c+a);}
    static String slovo(String a, String b, String c) {

        return slovo (a,b, c);
    }
}
