/*
напишите фрагмент класса, который будет присваивать значение 7,5 переменной х, а затем
переменным а и b будет присваивать значение вдвое и втрое (соответственно) большее значение переменной х
*/
public class Main {
    public static void main(String[]args){
        double x = 7.5;
        double a =x*2;
        double b =x*3;
        System.out.println("Переменная а: "+a);
        System.out.println("Переменная b: "+b);

    }
}
